### PR TITLE
Report Cable

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
:rocket:

### CODE REVIEW

**Review by mkllnk — COMMENTED** [review]
Amazing work, thank you. I reckon we get the email part merged first and then open this as a new pull request.

**Comment by Matt-Yorkley** [comment]
Cool. I think after they're both merged there's a little refactor that this controller desperately needs; there's various places in the `show` action and in the view where the code is effectively asking if the form has been posted or not and then branching in different directions based on the answer. 

It's crying out for the GET and POST requests to not be handled in the same controller action, and have them more clearly separated into two distinct actions closer to their respective REST verbs (`show` and `create` for GET and POST).

**Comment by mkllnk** [comment]
> It's crying out for the GET and POST requests to not be handled in the same controller action, and have them more clearly separated into two distinct actions closer to their respective REST verbs (show and create for GET and POST).

:100:

**Comment by mkllnk** [comment]
* Replaced by https://github.com/openfoodfoundation/openfoodnetwork/pull/10849

**Pull request closed without merging**
